### ISSUE TITLE
Incorrect Reward function : Assignment 1

### ISSUE THREAD

**Issue by KhadgaA** [manavmishra96/reinforcement-learning#3]
Sir, 
In the ` pull ` function, the `reward = np.random.randn(self.r_mean[index_arm], self.r_stddev[index_arm])` I believe shoud be `reward = np.random.normal(self.r_mean[index_arm], self.r_stddev[index_arm])`. Because I believe, `randn` returns an array of normal distribution values instead of one single value sampled from mean and sigma.  Please look into this. Thankyou.

**Comment by manavmishra96** [comment]
Thanks. I have updated the reward function!
